import { Inter } from "next/font/google";
import "./profile.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Association Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <main className="relative overflow-hidden">
        {children}
      </main>
      </body>
      </html>
  );
}

